services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.prod
    image: 4est-presentation:latest
    restart: unless-stopped
    env_file:
      - .env.production
    volumes:
      - storage_data:/var/www/storage/app
    networks:
      - presentation
      - fleet_fleet

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile.prod
    image: 4est-presentation-nginx:latest
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - presentation
      - fleet_fleet

volumes:
  storage_data:

networks:
  presentation:
  fleet_fleet:
    external: true
